name: graphql_schema
version: 1.0.4
description: An implementation of GraphQL's type system in Dart. Basis of graphql_server.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/graphql
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: ^1.15.0-nullsafety.4
  meta: ^1.0.0
dev_dependencies:
  lint: ^1.0.0
  test: ">=0.12.0 <2.0.0"