name: angel_graphql
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  angel_validate: ^1.0.0
  graphql_parser:
    path: ../graphql_parser
  graphql_schema:
    path: ../graphql_schema
  graphql_server:
    path: ../graphql_server
dev_dependencies:
  angel_serialize: ^2.0.0