name: graphql_generator
version: 1.0.0+1
description: Generates GraphQL schemas from Dart classes, for use with pkg:graphql_server.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/graphql
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  analyzer: ^2.1.0
  build: ^2.1.0
  build_config: ^1.0.0
  code_builder: ^4.1.0
  collection: ^1.15.0-nullsafety.4
  graphql_schema: ^1.0.2
  recase: ^4.0.0
  source_gen: ^1.1.0
dev_dependencies:
  build_runner: ^2.0.0
  lint: ^1.0.0

dependency_overrides:
  graphql_schema:
    path: ../graphql_schema