name: graphql_parser
version: 0.0.0
description: Parses GraphQL queries and schemas.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/graphql_parser
environment:
  sdk: ">=1.19.0"
dependencies: 
  source_span: ^1.0.0
  string_scanner: ^1.0.0
dev_dependencies:
  test: ^0.12.0
