targets:
  _standalone:
    sources:
      - lib/src/models/character.dart
      - lib/src/models/droid.dart
      - lib/src/models/starship.dart
  $default:
    dependencies:
      - ":_standalone"
    sources:
      - lib/src/models/human.dart