name: leto
version: 0.0.1
description: Base package for implementing GraphQL servers. You might prefer `package:angel_graphql`, the fastest way to implement GraphQL backends in Dart.
homepage: https://github.com/angel-dart/graphql
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  async: ^2.0.0
  collection: ^1.15.0-nullsafety.4
  crypto: ^3.0.0
  gql: ^0.13.0
  leto_schema:
    path: ../leto_schema
  meta: ^1.0.0
  source_span: ^1.0.0
  stream_channel: ^2.0.0
dev_dependencies:
  lint: ^1.0.0
  test: ">=0.12.0 <2.0.0"
