name: leto
version: 0.0.1
description: |
  Base package for implementing GraphQL servers. You might prefer `package:leto_shelf`
  for building GraphQL web server with leto and shelf.
homepage: https://github.com/juancastillo0/leto
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  async: ^2.0.0
  collection: ^1.15.0-nullsafety.4
  crypto: ^3.0.0
  gql: ^0.13.0
  leto_schema:
  meta: ^1.0.0
  source_span: ^1.0.0
  stream_channel: ^2.0.0
dev_dependencies:
  lint: ^1.0.0
  test: ">=0.12.0 <2.0.0"

dependency_overrides:
  leto_schema:
    path: ../leto_schema
  gql:
    git:
      url: https://github.com/juancastillo0/gql
      path: gql
      ref: e767a8dd62533f2ed8a1f9bd59187b4e838de204
