name: leto_generator
version: 0.0.1
description: Generates GraphQL schemas from Dart classes, for use with pkg:leto.
homepage: https://github.com/angel-dart/graphql
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  analyzer: ^2.1.0
  build: ^2.1.0
  build_config: ^1.0.0
  code_builder: ^4.1.0
  collection: ^1.15.0-nullsafety.4
  leto_schema:
    path: ../leto_schema
  recase: ^4.0.0
  source_gen: ^1.1.0
  json_annotation:
  freezed_annotation:
  valida:
  dart_style:
  glob:
  path:
dev_dependencies:
  build_runner: ^2.0.0
  lint: ^1.0.0
