name: leto_generator
version: 0.0.1-dev.4
description: Generates GraphQL schemas from Dart classes, for use with package:leto_schema.
repository: https://github.com/juancastillo0/leto

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ">=5.0.0 <7.0.0"
  build: ^2.4.0
  build_config: ^1.1.0
  code_builder: ^4.5.0
  source_gen: ^1.4.0

  collection: ^1.16.0
  recase: ^4.0.0
  json_annotation: ^4.7.0
  freezed_annotation: ^2.0.0

  dart_style: ^2.2.1
  glob: ^2.1.0
  path: ^1.8.2

  valida: ^0.2.0
  leto_schema: ^0.0.1-dev.3

dev_dependencies:
  lint: ^2.1.2
