name: leto_generator
version: 0.0.1
description: Generates GraphQL schemas from Dart classes, for use with package:leto_schema.
homepage: https://github.com/juancastillo0/leto

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.0.0
  build: ^2.3.0
  build_config: ^1.0.0
  code_builder: ^4.1.0
  source_gen: ^1.2.2

  collection: ^1.16.0
  recase: ^4.0.0
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.0

  dart_style: ^2.2.1
  glob: ^2.1.0
  path: ^1.8.2

  valida: ^0.0.2
  leto_schema:

dev_dependencies:
  lint: ^1.0.0

dependency_overrides:
  leto_schema:
    path: ../leto_schema
  valida:
    git:
      url: https://github.com/juancastillo0/valida
      path: valida
