name: leto_schema
version: 0.0.1
description: An implementation of GraphQL's type system in Dart. Basis of leto.
homepage: https://github.com/juancastillo0/leto

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0-nullsafety.4
  gql: ^0.13.0
  meta: ^1.0.0

dev_dependencies:
  lint: ^1.0.0
  test: ">=0.12.0 <2.0.0"

dependency_overrides:
  gql:
    git:
      url: https://github.com/juancastillo0/gql
      path: gql
      ref: e767a8dd62533f2ed8a1f9bd59187b4e838de204
