name: leto_schema
version: 0.0.1
description: An implementation of GraphQL's type system in Dart. Basis of leto.
homepage: https://github.com/juancastillo0/leto

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  gql: ^0.13.1
  meta: ^1.0.0

dev_dependencies:
  lint: ^1.0.0
  test: ^1.0.0

  leto_generator_example:

dependency_overrides:
  leto_generator_example:
    path: ../leto_generator/example
  leto:
    path: ../leto
