name: leto_schema
version: 0.0.1-dev.2
description: An implementation of GraphQL's type system in Dart. Basis of leto.
repository: https://github.com/juancastillo0/leto

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  gql: ^0.14.0
  meta: ^1.0.0
  source_span: ^1.0.0

dev_dependencies:
  lint: ^1.0.0
  test: ^1.0.0

  leto_generator_example:
  leto:

dependency_overrides:
  leto_generator_example:
    path: ../leto_generator/example
  leto:
    path: ../leto
