name: leto_shelf
description: Build GraphQL web servers with leto and shelf.
version: 0.0.1-dev.1
homepage: https://github.com/juancastillo0/leto

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.2
  freezed_annotation: ^2.0.0

  gql: ^1.0.0
  http_parser: ^4.0.0
  http_server: ^1.0.0
  mime: ^1.0.2

  json_annotation: ^4.7.0
  oxidized: ^6.0.0

  shelf: ^1.3.1
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.2.0

  leto: ^0.0.1-dev.1
  leto_schema: ^0.0.1-dev.3

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.3.5

  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  gql_websocket_link: ^1.1.0

  http: ^0.13.3
  json_serializable: ^6.2.0
  lint: ^2.1.2
  # tests
  toml: ^0.14.0
  test: ^1.0.0

  leto_shelf_example:
    path: ./example
