name: leto_shelf
description: Build GraphQL web servers with leto and shelf.
version: 0.0.1
homepage: https://github.com/juancastillo0/leto

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  crypto: ^3.0.0
  freezed_annotation: ^0.14.3

  gql: ^0.13.0
  leto:
  leto_schema:
  http_parser: ^4.0.0
  http_server: ^1.0.0

  json_annotation: ^4.3.0
  oxidized: ^5.0.1

  shelf: ^1.2.0
  shelf_web_socket: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.1
  freezed: ^0.14.5

  gql_exec:
  gql_link:
  gql_websocket_link:
    git:
      url: https://github.com/juancastillo0/gql
      path: links/gql_websocket_link
      ref: 813d52423ed1bff6db17e9c1dbe47cf489f06266

  http: ^0.13.3
  json_serializable: ^6.0.1
  lint: ^1.0.0
  # tests
  toml: ^0.12.0

  leto_shelf_example:
    path: ./example

  test: ^1.14.4

dependency_overrides:
  leto:
    path: ../leto
  leto_schema:
    path: ../leto_schema
  gql:
    git:
      url: https://github.com/juancastillo0/gql
      path: gql
      ref: e767a8dd62533f2ed8a1f9bd59187b4e838de204
