name: leto_shelf
description: Build GraphQL web servers with leto and shelf.
version: 0.0.1
homepage: https://github.com/juancastillo0/leto

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  freezed_annotation: ^2.0.0

  gql: ^0.13.1
  http_parser: ^4.0.0
  http_server: ^1.0.0

  json_annotation: ^4.6.0
  oxidized: ^5.2.0

  shelf: ^1.3.1
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.2.0

  leto:
  leto_schema:

dev_dependencies:
  build_runner: ^2.1.11
  freezed: 2.0.3

  gql_exec: ^0.4.0
  gql_link: ^0.4.2
  gql_websocket_link: ^0.3.3
  # path: ../../gql/links/gql_websocket_link/
  # git:
  #   url: https://github.com/juancastillo0/gql
  #   path: links/gql_websocket_link
  #   ref: 813d52423ed1bff6db17e9c1dbe47cf489f06266

  http: ^0.13.3
  json_serializable: ^6.2.0
  lint: ^1.0.0
  # tests
  toml: ^0.12.0
  test: ^1.0.0

  leto_shelf_example:
    path: ./example

dependency_overrides:
  leto:
    path: ../leto
  leto_schema:
    path: ../leto_schema
