targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      leto_generator|graphql_types:
        options:
          serializerSuffix: Serializer
          graphqlTypeSuffix: GraphQLType
          unionKeySuffix: Discriminant
          graphQLFieldSuffix: GraphQLField
          nullableFields: false
          omitFields: false
          customTypes:
            - name: Decimal
              import: "package:leto_generator_example/decimal.dart"
              getter: "decimalGraphQLType"
      leto_generator|graphql_resolvers:
        options:
          serializerSuffix: Serializer
          graphqlTypeSuffix: GraphQLType
          unionKeySuffix: Discriminant
          graphQLFieldSuffix: GraphQLField
          nullableFields: false
          omitFields: false
          customTypes:
            - name: Decimal
              import: "package:leto_generator_example/decimal.dart"
              getter: "decimalGraphQLType"
