name: leto_generator_example
version: 1.0.0+1
description: Example for leto_generator
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0-nullsafety.4
  leto_schema: ^1.0.2
  decimal: ^1.0.0
  json_annotation: ^4.3.0
  freezed_annotation:
  oxidized: ^5.1.0
  valida:
    git:
      url: https://github.com/juancastillo0/valida
      path: valida
  leto:
    path: ../../leto

dev_dependencies:
  build_runner: ^2.0.0
  lint: ^1.0.0
  freezed:
  json_serializable:
  leto_generator:
  valida_generator:
    git:
      url: https://github.com/juancastillo0/valida
      path: valida_generator

dependency_overrides:
  leto_generator:
    path: ../
  leto_schema:
    path: ../../leto_schema
    # git:
    #   url: https://github.com/juancastillo0/leto
    #   path: leto_schema
  valida:
    path: ../../../valida/valida
  leto:
    path: ../../leto
