name: leto_generator_example
description: Example for leto_generator

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  decimal: ^1.0.0
  json_annotation: ^4.6.0
  freezed_annotation: ^2.0.0
  oxidized: ^5.1.0
  test: ^1.0.0
  valida: ^0.1.0-dev.1

  leto:
  leto_schema:

dev_dependencies:
  build_runner: ^2.1.11
  lint: ^1.0.0
  freezed: 2.0.3
  json_serializable: ^6.2.0

  valida_generator: ^0.1.0-dev.1
  leto_generator:

dependency_overrides:
  leto_generator:
    path: ..
  leto:
    path: ../../leto
  leto_schema:
    path: ../../leto_schema
