name: leto_generator_example
description: Example for leto_generator

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.15.0-nullsafety.4
  leto_schema:
  decimal: ^1.0.0
  json_annotation: ^4.3.0
  freezed_annotation:
  oxidized: ^5.1.0
  valida:
  leto:

dev_dependencies:
  build_runner: ^2.0.0
  lint: ^1.0.0
  freezed:
  json_serializable:
  leto_generator:
  valida_generator:
  test:

dependency_overrides:
  leto_generator:
    path: ..
  leto:
    path: ../../leto
  leto_schema:
    path: ../../leto_schema
