name: leto_shelf_example
description: A sample Dart GraphQL server using leto_shelf.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.0
  json_annotation: ^4.6.0
  json_path: ^0.3.0
  oxidized: ^5.0.1

  sqlite3: ^1.3.1
  mysql1: ^0.19.2
  postgres: ^2.4.1+2

  shelf_plus: ^0.0.2
  shelf_router: ^1.1.1
  shelf_static: ^1.1.0

  valida:
  query_builder:
    git: https://github.com/juancastillo0/query_builder

  leto_shelf:
  leto_schema:
  leto:

dev_dependencies:
  build_runner: ^2.1.11
  freezed: 2.0.3
  http: ^0.13.3
  json_serializable: ^6.2.0
  lint: ^1.0.0
  test: ^1.0.0

  leto_generator:
  valida_generator:
  query_builder_generator:
    git:
      url: https://github.com/juancastillo0/query_builder
      path: query_builder_generator

dependency_overrides:
  leto_generator:
    path: ../../leto_generator
  leto_shelf:
    path: ..
  leto:
    path: ../../leto
  leto_schema:
    path: ../../leto_schema
