name: server
description: A chat server app using leto, shelf and Docker.
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.0.0
  freezed_annotation: ^2.0.0
  json_annotation: ^4.7.0
  json_path: ^0.3.0
  oxidized: ^5.0.1
  blurhash_dart: ^1.0.2
  metadata_fetch: ^0.4.1
  linkify: ^4.1.0
  crypto: ^3.0.2
  file: ^6.1.2

  sqlite3: ^1.3.1
  mysql1: ^0.19.2
  postgres: ^2.4.1+2

  argon2: ^1.0.1
  jose: ^0.3.2

  uuid: ^3.0.6
  collection: ^1.16.0

  shelf_cors_headers: ^0.1.2
  shelf_plus: ^0.0.2
  shelf_router: ^1.1.1
  shelf_static: ^1.1.0

  valida: ^0.1.0-dev.1
  query_builder:
    git: https://github.com/juancastillo0/query_builder

  leto_shelf:
  leto_shelf_example:
  leto:
  leto_schema:

dev_dependencies:
  build_runner: ^2.1.11
  freezed: 2.0.3
  http: ^0.13.3
  json_serializable: ^6.2.0
  lint: ^1.0.0
  test_process: ^2.0.0
  test: ^1.0.0

  gql_exec: ^0.4.0
  gql_link: ^0.4.2
  gql_websocket_link: ^0.3.3
  # path: ../../../gql/links/gql_websocket_link/
  # git:
  #   url: https://github.com/juancastillo0/gql
  #   path: links/gql_websocket_link
  #   ref: 813d52423ed1bff6db17e9c1dbe47cf489f06266
  gql: ^0.14.0

  leto_generator:
  valida_generator: ^0.1.0-dev.1
  query_builder_generator:
    git:
      url: https://github.com/juancastillo0/query_builder
      path: query_builder_generator

dependency_overrides:
  leto_generator:
    path: ../../leto_generator
  leto:
    path: ../../leto
  leto_schema:
    path: ../../leto_schema
  leto_shelf:
    path: ../../leto_shelf
  leto_shelf_example:
    path: ../../leto_shelf/example
