targets:
  $default:
    builders:
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: chat_example|lib/api_schema.graphql
          custom_serializers:
            - import: "package:chat_example/api/upload_serializer.dart"
              name: UploadSerializer
          type_overrides:
            Upload:
              name: MultipartFile
              import: "package:http/http.dart"
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: chat_example|lib/api_schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: "package:http/http.dart"
